SELECT FIRST_NAME, SALARY FROM worker; # Order of execution Right to Left from 'FROM'

SELECT now(); -- Gives current time

SELECT 22+11;

SELECT lcase("AnkIt");

SELECT * FROM worker WHERE SALARY>200000;
SELECT * FROM worker WHERE DEPARTMENT='HR';

SELECT * FROM worker WHERE SALARY BETWEEN 300000 AND 500000;

# HR and Admin department -> workers : OR
 SELECT * FROM worker WHERE DEPARTMENT = 'HR' OR DEPARTMENT='Admin';
 SELECT * FROM worker WHERE DEPARTMENT = 'HR' OR DEPARTMENT='Admin' OR DEPARTMENT='Account';
 
 # Better Way : IN 
SELECT * FROM worker WHERE DEPARTMENT IN ('HR','Admin','Account');

# NOT 
SELECT * FROM worker WHERE DEPARTMENT NOT IN ('HR','Account');

-- Regex/WILDCARD
SELECT * FROM worker WHERE LAST_NAME LIKE '%a_';

-- SORTING using ORDER BY 
SELECT * FROM worker ORDER BY SALARY; -- By default ascending
SELECT * FROM worker ORDER BY SALARY DESC; -- Descending 

-- DISTINCT
SELECT DISTINCT DEPARTMENT FROM worker;

-- GROUPING
SELECT DEPARTMENT FROM worker GROUP BY DEPARTMENT;
SELECT DEPARTMENT,COUNT(*) FROM worker GROUP BY DEPARTMENT;
-- SELECT DEPARTMENT,COUNT(DEPARTMENT) FROM worker GROUP BY DEPARTMENT;

-- Q: AVERAGE SALARY PER DEPARTMENT
SELECT DEPARTMENT, AVG(SALARY) FROM worker GROUP BY DEPARTMENT;
-- Q: MIN. SALARY PER DEPARTMENT
SELECT DEPARTMENT, MIN(SALARY) FROM worker GROUP BY DEPARTMENT;
-- Q: MAX. SALARY PER DEPARTMENT
SELECT DEPARTMENT, MAX(SALARY) FROM worker GROUP BY DEPARTMENT;
-- Q: TOTAL SALARY PER DEPARTMENT
SELECT DEPARTMENT, SUM(SALARY) FROM worker GROUP BY DEPARTMENT;

-- HAVING
SELECT DEPARTMENT, COUNT(DEPARTMENT) FROM worker GROUP BY DEPARTMENT HAVING COUNT(DEPARTMENT)>2;
SELECT DEPARTMENT, COUNT(*) FROM worker GROUP BY DEPARTMENT HAVING COUNT(DEPARTMENT)>2;